name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install modules
        run: npm install eslint @electron-toolkit/eslint-config eslint-plugin-vue @vue/eslint-config-prettier

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download ffmpeg-libs
        uses: dawidd6/action-download-artifact@v7
        with:
          repo: elya5/ffmpeg-build
          github_token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          name: ffmpeg-libs-linux
          path: ffmpeglibs
          workflow: blank.yml
          check_artifacts: true
          search_artifacts: true

      - name: Test pip and python
        run: |
          pip --version
          python --version

      - name: Install uv
        run: pip install uv

      - name: Build venv
        run: |
          cd server
          uv venv
          uv add pyright

      - name: Run ruff
        run: ruff check

      - name: Run pyright
        run: uv run pyright
