name: Create Release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Workflow Run
        id: get-run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_run=$(gh run list --workflow=build_electron.yml --limit 1 --json databaseId,status --jq '.[] | select(.status == "completed") | .databaseId')
          echo "run_id=$latest_run" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.get-run.outputs.run_id }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/vian-lite-linux*
            **/vian-lite-win*
            **/vian-lite-mac*
          tag_name: ${{ github.event.inputs.release-tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
